version: "3.9"
services:
  opensearch:
    image: my-opensearch-ingest:latest
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ngP@ssw0rd!
    ports:
      - "9200:9200"
